---
- name: PCTN Ansible Trial
  connection: local
  gather_facts: false 
  hosts: PCTN
  vars:
          #contents: "{{ lookup('file', '/root/pctn/scripts/ansible/raw_banner.txt') }}"
  tasks:
    - name: Trying Huawei module
      ce_command:
#      when: ansible_network_os == 'ios'
         commands: 
             - display clock
             - tftp -a {{ ansible_host }} 172.29.137.20 ge test.txt cfcard:/test2.txt
               #             - disp acl name aclREMOTE_ACCESS 
               #             - display accounting-scheme tacacs_plus 
      register: output
      #    - name: configure the login banner
      #ce_banner:
      #  lines: 
      #     - header login information ^
      #      ______________ FOR STARHUB AUTHORIZED USERS ONLY __________________
      #     If you are not authorized to access this equipment of network, 
      #      please disconnect immediately.
      #      ^
    - name: Display output
      debug:
        var: output.stdout_lines[0]
